<a href="https://colab.research.google.com/github/Shashwat-006/Learning_PyTorch/blob/main/Learning_PyTorch_Basics_6.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

This is just for learning how the pipeline for a neural network works in PyTorch from basics by coding everything manually rather than using modules provided by Pytorch

In [68]:
import numpy as np
import pandas as pd
import torch
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder

# **Basic Operations for the Model**

In [69]:
data = pd.read_csv('/content/breast-cancer.csv')

In [70]:
data.head()

         id diagnosis  ...  symmetry_worst  fractal_dimension_worst
0    842302         M  ...          0.4601                  0.11890
1    842517         M  ...          0.2750                  0.08902
2  84300903         M  ...          0.3613                  0.08758
3  84348301         M  ...          0.6638                  0.17300
4  84358402         M  ...          0.2364                  0.07678

[5 rows x 32 columns]

In [71]:
Y = data['diagnosis']
X = data.drop(columns =['id','diagnosis'],axis=1)

In [72]:
X.head()

   radius_mean  texture_mean  ...  symmetry_worst  fractal_dimension_worst
0        17.99         10.38  ...          0.4601                  0.11890
1        20.57         17.77  ...          0.2750                  0.08902
2        19.69         21.25  ...          0.3613                  0.08758
3        11.42         20.38  ...          0.6638                  0.17300
4        20.29         14.34  ...          0.2364                  0.07678

[5 rows x 30 columns]

In [73]:
X.shape

(569, 30)

Train Test Split

In [74]:
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.2)

Standardizing the data

In [75]:
scaler = StandardScaler()

In [76]:
X_train = scaler.fit_transform(X_train)
X_test = scaler.fit_transform(X_test)

Converting diagnosis column to numerical values

In [77]:
encoder = LabelEncoder()

In [78]:
Y_train = encoder.fit_transform(Y_train)
Y_test = encoder.transform(Y_test)

In [79]:
Y_train

array([0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0,
       1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0,
       0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0,
       0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0,
       0, 0, 1, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0,
       0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1,
       0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1,
       0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1,
       1, 1, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0,
       1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1,
       0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0,
       0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1,
       1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1,
       0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0,
       1, 0, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1,
       1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0,
       0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 1])

Numpy arrays to PyTorch TENSORS

In [80]:
X_train_tensor = torch.from_numpy(X_train)
X_test_tensor = torch.from_numpy(X_test)
Y_train_tensor = torch.from_numpy(Y_train)
Y_test_tensor = torch.from_numpy(Y_test)

In [81]:
X_train_tensor

tensor([[-0.8198, -0.0596, -0.8463,  ..., -0.6701, -0.8355, -0.9724],
        [ 1.0725,  0.2970,  1.0550,  ...,  0.5226,  0.5951, -0.4192],
        [ 2.0215, -0.9839,  1.9893,  ...,  1.2401, -0.2807,  0.1660],
        ...,
        [ 1.5753,  1.3668,  1.5446,  ...,  0.8881,  0.6859,  0.0530],
        [-0.1560, -0.0385, -0.1258,  ...,  0.3993, -0.2572,  0.2633],
        [-0.5289,  1.7750, -0.4648,  ...,  0.4775,  0.5346,  2.0685]],
       dtype=torch.float64)

# **Defining the Model**

In [82]:
class firstNN():
  def __init__(self,X):
    self.weights = torch.rand(X.shape[1], 1, dtype=torch.float64, requires_grad=True) #taking a random value at first then will change it accordingly
    self.bias = torch.zeros(1, dtype=torch.float64, requires_grad=True)

  def forward(self, X):
    z = torch.matmul(X, self.weights) + self.bias
    y_pred = torch.sigmoid(z)
    return y_pred

  def loss_function(self, y_pred, y): #binary cross entropy loss
    epsilon = 1e-7 #avoiding log(0) condition
    y_pred = torch.clamp(y_pred, epsilon, 1-epsilon)

    #loss calculation
    loss = -(y * torch.log(y_pred) + (1 - y) * torch.log(1 - y_pred)).mean()
    return loss

# **Important Parameters**

In [83]:
learning_rate = 0.1
no_of_epochs = 40

# **Training Pipeline**

In [84]:
#creating model
model = firstNN(X_train_tensor)

for epochs in range(no_of_epochs):

  #forward pass
  y_pred = model.forward(X_train_tensor)

  #loss calculation
  loss = model.loss_function(y_pred, Y_train_tensor)

  #backward pass
  loss.backward()

  #parameters updation
  with torch.no_grad():
    model.weights -= learning_rate * model.weights.grad
    model.bias -= learning_rate * model.bias.grad

  #zero gradients so that gradients doesn't accumulate
  model.weights.grad.zero_()
  model.bias.grad.zero_()

  #visualizing loss with each epoch
  print(f'Epoch: {epochs+1}, Loss: {loss.item()}')

Epoch: 1, Loss: 3.5046924730559277
Epoch: 2, Loss: 3.3656173303530323
Epoch: 3, Loss: 3.2218433784374643
Epoch: 4, Loss: 3.073589172544232
Epoch: 5, Loss: 2.9180483679580895
Epoch: 6, Loss: 2.7551788963957113
Epoch: 7, Loss: 2.5895213391001453
Epoch: 8, Loss: 2.4237618135645147
Epoch: 9, Loss: 2.2511057566313215
Epoch: 10, Loss: 2.0762877819367693
Epoch: 11, Loss: 1.9086097389296395
Epoch: 12, Loss: 1.747326134775053
Epoch: 13, Loss: 1.5889422975376917
Epoch: 14, Loss: 1.4431839328974279
Epoch: 15, Loss: 1.3120089691505252
Epoch: 16, Loss: 1.197317433194914
Epoch: 17, Loss: 1.1007061350013412
Epoch: 18, Loss: 1.022949131433224
Epoch: 19, Loss: 0.963315812172438
Epoch: 20, Loss: 0.9193482756710202
Epoch: 21, Loss: 0.8875075424860898
Epoch: 22, Loss: 0.8642164098077052
Epoch: 23, Loss: 0.8465878162540099
Epoch: 24, Loss: 0.8326099936690377
Epoch: 25, Loss: 0.8209992120215076
Epoch: 26, Loss: 0.8109735889021379
Epoch: 27, Loss: 0.8020657375284104
Epoch: 28, Loss: 0.7939958856374251
Epoch: 29, Loss: 0.7865934183211073
Epoch: 30, Loss: 0.7797504989784902
Epoch: 31, Loss: 0.7733952894007671
Epoch: 32, Loss: 0.7674766894617641
Epoch: 33, Loss: 0.7619557131484725
Epoch: 34, Loss: 0.7568006434289524
Epoch: 35, Loss: 0.7519843214145614
Epoch: 36, Loss: 0.74748263256401
Epoch: 37, Loss: 0.7432736595063963
Epoch: 38, Loss: 0.739337203140939
Epoch: 39, Loss: 0.7356545052548636
Epoch: 40, Loss: 0.7322080801027222

In [85]:
model.bias

tensor([-0.2865], dtype=torch.float64, requires_grad=True)

# **Evaluation**

In [86]:
#model evaluation
with torch.no_grad():
  y_pred = model.forward(X_test_tensor).round()
  accuracy = (y_pred == Y_test_tensor).float().mean()
  print(f'Accuracy: {accuracy}')

Accuracy: 0.5554016828536987