<a href="https://colab.research.google.com/github/Shashwat-006/Learning_PyTorch/blob/main/Linearr_Regression_PyTorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [53]:
import torch
from torch import nn
import pandas as pd

In [54]:
dataset = pd.read_csv('/content/salary_data.csv')

In [55]:
dataset.head()

   YearsExperience  Salary
0              1.1   39343
1              1.3   46205
2              1.5   37731
3              2.0   43525
4              2.2   39891

In [56]:
y = dataset['Salary']
x = dataset.drop(columns = ['Salary'])

In [57]:
x.head()

   YearsExperience
0              1.1
1              1.3
2              1.5
3              2.0
4              2.2

In [58]:
from sklearn.preprocessing import StandardScaler

In [59]:
scalar = StandardScaler()

In [60]:
x = scalar.fit_transform(x)

In [61]:
y = y.to_numpy().reshape(-1, 1)
y = scalar.fit_transform(y)

In [62]:
print(y.shape)

(30, 1)

In [63]:
from sklearn.model_selection import train_test_split

In [64]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.2, random_state=17)

In [65]:
x_train = torch.tensor(x_train , dtype = torch.float32)
x_test = torch.tensor(x_test , dtype = torch.float32)
y_train = torch.tensor(y_train, dtype = torch.float32)
y_test = torch.tensor(y_test, dtype = torch.float32)

In [66]:
model = nn.Sequential(
    nn.Linear(1, 1)
)

In [67]:
loss_fn = nn.MSELoss()

optimizer = torch.optim.SGD(model.parameters(), lr = 0.01)

In [68]:
y_train.shape

torch.Size([24, 1])

In [69]:
model(x_train).shape

torch.Size([24, 1])

In [70]:
print("Weight: ", model[0].weight)

Weight:  Parameter containing:
tensor([[0.2553]], requires_grad=True)

In [71]:
for epoch in range(300):
  y_pred = model(x_train)
  loss = loss_fn(y_pred, y_train)

  optimizer.zero_grad()
  loss.backward()
  optimizer.step()

  if epoch % 10 == 0:
    print(f'Epoch {epoch}, Loss {loss.item():.4f}')

Epoch 0, Loss 1.3367
Epoch 10, Loss 0.8844
Epoch 20, Loss 0.5901
Epoch 30, Loss 0.3984
Epoch 40, Loss 0.2736
Epoch 50, Loss 0.1923
Epoch 60, Loss 0.1394
Epoch 70, Loss 0.1049
Epoch 80, Loss 0.0824
Epoch 90, Loss 0.0678
Epoch 100, Loss 0.0582
Epoch 110, Loss 0.0520
Epoch 120, Loss 0.0479
Epoch 130, Loss 0.0453
Epoch 140, Loss 0.0436
Epoch 150, Loss 0.0424
Epoch 160, Loss 0.0417
Epoch 170, Loss 0.0412
Epoch 180, Loss 0.0409
Epoch 190, Loss 0.0407
Epoch 200, Loss 0.0406
Epoch 210, Loss 0.0405
Epoch 220, Loss 0.0404
Epoch 230, Loss 0.0404
Epoch 240, Loss 0.0404
Epoch 250, Loss 0.0404
Epoch 260, Loss 0.0403
Epoch 270, Loss 0.0403
Epoch 280, Loss 0.0403
Epoch 290, Loss 0.0403

In [72]:
print(model[0].weight)

Parameter containing:
tensor([[0.9632]], requires_grad=True)

In [73]:
model.eval()

with torch.no_grad():
    y_pred = model(x_test)
    test_loss = loss_fn(y_pred, y_test)

print("Test Loss:", test_loss.item())

Test Loss: 0.05782264098525047

In [74]:
from sklearn.metrics import r2_score

model.eval()

with torch.no_grad():
    y_pred = model(x_test).numpy()

r2 = r2_score(y_test.numpy(), y_pred)

print("R² Score:", r2)

R² Score: 0.9379496574401855