<a href="https://colab.research.google.com/github/Shashwat-006/Learning_PyTorch/blob/main/Logistic_Regression_PyTorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [131]:
import torch
from torch import nn
import pandas as pd

In [132]:
dataset = pd.read_csv('/content/diabetes.csv')

In [133]:
dataset.head()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148,72,35,0,33.6,0.627,50,1
1,1,85,66,29,0,26.6,0.351,31,0
2,8,183,64,0,0,23.3,0.672,32,1
3,1,89,66,23,94,28.1,0.167,21,0
4,0,137,40,35,168,43.1,2.288,33,1

In [134]:
dataset['Outcome'].value_counts()

Outcome
0    500
1    268
Name: count, dtype: int64

In [135]:
y = dataset['Outcome']
x = dataset.drop(columns = ['Outcome'])

In [136]:
x.head()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age
0,6,148,72,35,0,33.6,0.627,50
1,1,85,66,29,0,26.6,0.351,31
2,8,183,64,0,0,23.3,0.672,32
3,1,89,66,23,94,28.1,0.167,21
4,0,137,40,35,168,43.1,2.288,33

In [137]:
from sklearn.model_selection import train_test_split

In [138]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.2,  stratify = y)

In [139]:
from sklearn.preprocessing import StandardScaler

In [140]:
scalar = StandardScaler()

In [141]:
x_train = scalar.fit_transform(x_train)

In [142]:
x_test = scalar.transform(x_test)

In [143]:
print(type(x_train))

<class 'numpy.ndarray'>

In [144]:
x_train = torch.tensor(x_train , dtype = torch.float32)
x_test = torch.tensor(x_test , dtype = torch.float32)
y_train = torch.tensor(y_train.values, dtype = torch.float32)
y_test = torch.tensor(y_test.values, dtype = torch.float32)

In [145]:
model = nn.Sequential(
    nn.Linear(8, 1),
    nn.Sigmoid()
)

In [146]:
loss_fn = nn.BCELoss()

In [147]:
optimizer = torch.optim.Adam(model.parameters(), lr = 0.01)

In [148]:
print(model[0].weight)

Parameter containing:
tensor([[ 0.0866,  0.0993,  0.2657, -0.1371,  0.0984,  0.0865, -0.0191, -0.0112]],
       requires_grad=True)

In [149]:
for epoch in range (200):
  y_pred = model(x_train).squeeze()
  loss = loss_fn(y_pred, y_train)

  optimizer.zero_grad()
  loss.backward()
  optimizer.step()

  if epoch % 10 == 0:
    print(f'Epoch {epoch}, Loss {loss.item():.4f}')

Epoch 0, Loss 0.6370
Epoch 10, Loss 0.5775
Epoch 20, Loss 0.5425
Epoch 30, Loss 0.5202
Epoch 40, Loss 0.5056
Epoch 50, Loss 0.4954
Epoch 60, Loss 0.4881
Epoch 70, Loss 0.4829
Epoch 80, Loss 0.4793
Epoch 90, Loss 0.4767
Epoch 100, Loss 0.4748
Epoch 110, Loss 0.4735
Epoch 120, Loss 0.4725
Epoch 130, Loss 0.4718
Epoch 140, Loss 0.4713
Epoch 150, Loss 0.4710
Epoch 160, Loss 0.4707
Epoch 170, Loss 0.4706
Epoch 180, Loss 0.4704
Epoch 190, Loss 0.4704

In [150]:
print(model[0].weight)

Parameter containing:
tensor([[ 0.4157,  1.0206, -0.2121, -0.0815, -0.0495,  0.8087,  0.2437,  0.1660]],
       requires_grad=True)

In [151]:
model.eval()

with torch.no_grad():
  train_pred = model(x_train)
  train_pred = (train_pred > 0.5).float()
  test_pred = model(x_test)
  test_pred = (test_pred > 0.5).float()


  train_acc = (train_pred.squeeze() == y_train).float().mean()
  print(f'Train Accuracy {train_acc.item()*100:.2f}')

  test_acc = (test_pred.squeeze() == y_test).float().mean()
  print(f'Test Accuracy {test_acc.item()*100:.2f}')

Train Accuracy 77.36
Test Accuracy 79.87